//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    [Serializable]
    public partial class client
    {
        
        public client()
        {
            this.order = new HashSet<order>();
        }
    
        public int idClient { get; set; }
        public string FirstName { get; set; }
        public string SecondName { get; set; }
        public string ThirdName { get; set; }
        public string Phone { get; set; }
        public Nullable<System.DateTime> Birth { get; set; }
    
        public virtual ICollection<order> order { get; set; }
    }
}
