//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    [Serializable]
    public partial class order
    {
        public int idorder { get; set; }
        public string workname { get; set; }
        public Nullable<System.DateTime> beginTime { get; set; }
        public Nullable<System.DateTime> endTime { get; set; }
        public Nullable<int> cost { get; set; }
        public Nullable<int> idclient { get; set; }
        public Nullable<int> idauto { get; set; }
    
        public virtual auto auto { get; set; }
        public virtual client client { get; set; }
    }
}
