//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication1
{
    using System;
    using System.Collections.Generic;
    [Serializable]
    public partial class auto
    {
        public auto()
        {
            this.order = new HashSet<order>();
        }
    
        public int idauto { get; set; }
        public string mark { get; set; }
        public string model { get; set; }
        public Nullable<int> horsePower { get; set; }
        public Nullable<int> year { get; set; }
        public string transmission { get; set; }
    
        public virtual ICollection<order> order { get; set; }
    }
}
