//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication1
{
    using System;
    using System.Collections.Generic;
    [Serializable]
    public partial class client
    {
        public client()
        {
            this.order = new HashSet<order>();
        }
    
        public int idClient { get; set; }
        public string FirstName { get; set; }
        public string SecondName { get; set; }
        public string ThirdName { get; set; }
        public string Phone { get; set; }
        public Nullable<System.DateTime> Birth { get; set; }
    
        public virtual ICollection<order> order { get; set; }
    }
}
