//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        public int idorder { get; set; }
        public string workname { get; set; }
        public Nullable<System.DateTime> beginTime { get; set; }
        public Nullable<System.DateTime> endTime { get; set; }
        public Nullable<int> cost { get; set; }
        public Nullable<int> idclient { get; set; }
        public Nullable<int> idauto { get; set; }
    
        public virtual auto auto { get; set; }
        public virtual client client { get; set; }
    }
}
